import { notFound } from 'next/navigation'

import pageMetadata from '@/lib/metadata/page'
import Nav from '@/components/Dashboard/Nav'
import SetImagePageState from './SetState'
import Images from './Images'
import imageCompletionFromId from '@/lib/image/fromId'
import ImageCompletion from '@/lib/image'
import imageCompletionUrlFromId from '@/lib/image/urlFromId'

export const generateMetadata = async ({
	params: { imageId: encodedImageId }
}: {
	params: { imageId: string }
}) => {
	const imageId = decodeURIComponent(encodedImageId)

	const image = await imageCompletionFromId(imageId)
	if (!image) return {}

	return pageMetadata({
		title: `${image.prompt} | Images | TryGPT`,
		description: `View "${image.prompt}" generated by DALL-E 2. TryGPT is the cheapest way to get access to GPT-4 which is far, far superior to the free GPT-3.5. Start now for only $1.`,
		previewImage: imageCompletionUrlFromId(image.id)
	})
}

const ImagePage = async ({
	params: { imageId: encodedImageId }
}: {
	params: { imageId: string }
}) => {
	const imageId = decodeURIComponent(encodedImageId)

	const image = await imageCompletionFromId(imageId)
	if (!image) notFound()

	const expandedImage: ImageCompletion = { ...image, expanded: true }

	return (
		<>
			<SetImagePageState image={expandedImage} />
			<Nav>{expandedImage.prompt}</Nav>
			<main className="overflow-y-auto">
				<Images />
			</main>
		</>
	)
}

export default ImagePage
