DO $$ BEGIN CREATE DOMAIN USER_ID TEXT;
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN USER_PHOTO TEXT CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN USER_NAME VARCHAR(150) CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN USER_EMAIL TEXT CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS users (
	id USER_ID NOT NULL PRIMARY KEY,
	photo USER_PHOTO,
	name USER_NAME NOT NULL,
	email USER_EMAIL NOT NULL UNIQUE,
	created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
